version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build:     
    docker: # run the steps with Docker
      - image: circleci/node:4.8.2 # ...with this image as the primary container; this is where all `steps` will run      
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'      
      - run:
          name: install-npm-dependencies
          command: sudo npm install      
      - run: 
          name: compile
          command: sudo npm run build      
