version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build:     
    docker: # run the steps with Docker
      - image: circleci/node
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory      
      - run:
          name: install-npm-dependencies
          command: npm install      
      - run: 
          name: compile
          command: npm run build      
